//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSample.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopSample.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   利用規約への同意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自己紹介 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   誕生日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}にチェックを入れてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckboxRequiredError {
            get {
                return ResourceManager.GetString("CheckboxRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が{1}と一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompareError {
            get {
                return ResourceManager.GetString("CompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード（確認） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を正しい形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   性別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   趣味（複数選択可） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputRequiredError {
            get {
                return ResourceManager.GetString("InputRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いつも使う支払い方法 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は必須入力です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectRequiredError {
            get {
                return ResourceManager.GetString("SelectRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{2}文字以上、{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringLengthRangeError {
            get {
                return ResourceManager.GetString("StringLengthRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
